# Generated by Django 4.1.7 on 2023-02-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='projects',
        ),
    ]
