# Generated by Django 4.1.7 on 2023-02-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag_projects_vote_ratio_projects_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='project',
        ),
    ]
